"""Updated At field added

Revision ID: 052fb8c7d214
Revises: fc296b072a98
Create Date: 2019-02-09 14:16:14.656320

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '052fb8c7d214'
down_revision = 'fc296b072a98'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('measurand', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('measurand', 'updated_at')
    # ### end Alembic commands ###
