"""CO field added

Revision ID: fa9a59bf6c51
Revises: 052fb8c7d214
Create Date: 2019-02-09 23:37:22.271939

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa9a59bf6c51'
down_revision = '052fb8c7d214'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('measurand', sa.Column('co', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('measurand', 'co')
    # ### end Alembic commands ###
